apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app.kubernetes.io/name: teste-deploy-openshift # your application name
  name: teste-deploy-openshift # your application name
spec:
  output:
    to:
      kind: DockerImage
      name: dockerfile # add yourimage
  source:
    # Expect a local directory to be streamed to OpenShift as a build source
    type: Binary
    binary: {}
  strategy:
    type: Docker
    dockerStrategy:
      # Find the image build instructions in./Dockerfile
      dockerfilePath: ./src/main/docker/Dockerfile
